### PR TITLE
Fix Ogmios connection errors

### LINKED ISSUE #42: Incorrect behavior with not fully synced Ogmios
The problem manifests when you try to establish a connection with Ogmios when it's not fully synced (in my case when you start the application and Ogmios simultaneously). The connection seems to be established because I get logs from the `handle_connect/1` callback, but when the client tries to send frames to Ogmios it fails with the following error:

```
[info] Connected to Ogmios
[error] :gen_statem OgmiosChainSyncClient terminating
** (FunctionClauseError) no function clause matching in :websocket_client.disconnected/3
    (websocket_client 1.5.0) /home/arjaz/code/xxxxxx/deps/websocket_client/src/websocket_client.erl:313: :websocket_client.disconnected(:cast, {:cast_frame, {:text, "{\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"nextBlock\",\n  \"id\": \"initial_sync\"\n}\n"}}, {:context, {:websocket_req, :ws, ~c"0.0.0.0", 1337, ~c"/", 5000, #Reference<0.2003193081.4165206023.17349>, 1, #Port<0.21>, {:transport, :gen_tcp, :tcp, :tcp_closed, :tcp_error, [mode: :binary, active: true, packet: 0]}, "xxxxxx", :undefined, 1, :undefined, :undefined, :undefined}, {:transport, :gen_tcp, :tcp, :tcp_closed, :tcp_error, [mode: :binary, active: true, packet: 0]}, [], {:ws, ~c"0.0.0.0", 1337, ~c"/"}, {OgmiosChainSyncClient, %{restart: :permanent, handler: OgmiosChainSyncClient, start_slot: 63877794, start_block_id: "3ada6acb25b72f4540a1047fe0ad14744bdea505106863a5d7dc655e96386f05", sync_from: %{point: %{id: "6cdb572be812026c342108c6e9856ccf36e7c971d548305cc3362c43762e749d", slot: 70870715}}, ws_pid: #PID<0.455.0>}}, "", true, 0})
    (stdlib 6.0.1) gen_statem.erl:3113: :gen_statem.loop_state_callback/11
    (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Queue: [cast: {:cast_frame, {:text, "{\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"nextBlock\",\n  \"id\": \"initial_sync\"\n}\n"}}]
Postponed: []
State: {:disconnected, {:context, {:websocket_req, :ws, ~c"0.0.0.0", 1337, ~c"/", 5000, #Reference<0.2003193081.4165206023.17349>, 1, #Port<0.21>, {:transport, :gen_tcp, :tcp, :tcp_closed, :tcp_error, [mode: :binary, active: true, packet: 0]}, "xxxxxx", :undefined, 1, :undefined, :undefined, :undefined}, {:transport, :gen_tcp, :tcp, :tcp_closed, :tcp_error, [mode: :binary, active: true, packet: 0]}, [], {:ws, ~c"0.0.0.0", 1337, ~c"/"}, {OgmiosChainSyncClient, %{restart: :permanent, handler: OgmiosChainSyncClient, start_slot: 63877794, start_block_id: "3ada6acb25b72f4540a1047fe0ad14744bdea505106863a5d7dc655e96386f05", sync_from: %{point: %{id: "6cdb572be812026c342108c6e9856ccf36e7c971d548305cc3362c43762e749d", slot: 70870715}}, ws_pid: #PID<0.455.0>}}, "", true, 0}}
Callback mode: :state_functions, state_enter: false
```

The connection doesn't get restored after that, but it doesn't get disconnected either as the `handle_disconnect/2` callback isn't called. Here are the relevant parts of the client I have:
```elixir
defmodule OgmiosChainSyncClient do
  use Xogmios, :chain_sync

  def start_link(opts) do
    last_processed_block = Query.last_block()
    initial_state =
        [
          sync_from: %{
            point: %{
              slot: last_processed_block.slot,
              id: last_processed_block.hash
            }
          }
        ]
    opts = Keyword.merge(opts, initial_state)
    Xogmios.start_chain_sync_link(__MODULE__, opts)
  end

  @impl true
  def handle_connect(state) do
    Logger.info("Connected to Ogmios")
    {:ok, state}
  end

  @impl true
  def handle_disconnect(_reason, state) do
    Logger.warning("Ogmios connection died, closing the connection")
    {:close, :disconnect, state}
  end

  @impl true
  def handle_block(block, state) do
    {:ok, :next_block, state}
  end
end

```

### PR DESCRIPTION
**Pull request by caike**
The errors would take place when there were issues with the underlying Cardano node - typically when the node is still starting and not yet fully synced. The Ogmios service is able to start and receive connections but the handshake is never completed and the client errors out when trying to send frames.

With this fix, Xogmios now displays errors/warnings for the following:

* Node is still starting up and no socket file is yet available

```
[error] Ogmios reported error: Ogmios service error. Cardano Node not ready.
Trying reconnection in 5 seconds.
```

* Socket file is available but node is still syncing with the network

```bash
[warning] Cardano Node not ready. Network sync progress at 62.881% Trying reconnection in 5 seconds.
[warning] Cardano Node not ready. Network sync progress at 62.883% Trying reconnection in 5 seconds.
```

Fixes #42

### CODE REVIEW

File: lib/xogmios/health_check.ex [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+
+  @http_client :httpc
+
+  @spec run(url :: String.t()) :: :ok | {:error, String.t()}
+  def run(ogmios_url) do
+    url = parse_url(ogmios_url)
+
+    # NOTE: Investigate if there's a better way to start these.
+    :inets.start()
+    :ssl.start()
```
Comment (caike) [inline lib/xogmios/health_check.ex:15]: The better way is to replace all this nonsense with simply using [Req](https://hex.pm/packages/req)
